### PR TITLE
Added a workaround for things like Steam Controllers

### PR DESCRIPTION
**Pull request by kode54**
This fixes OpenEmu/OpenEmu#2306

### CODE REVIEW

**Comment by drewhoener** [comment]
Any updates to this? I'd really love to have my steam controller work as a recognized input :)

**Comment by Weenie34** [comment]
How do I use it?

**Comment by kode54** [comment]
You need to do the following:

1) Install Steam and open it.
2) Open Steam Big Picture Mode by clicking the controller icon in the top right of the window.
3) Install controller drivers as necessary from Big Picture mode.
4) Navigate to the configuration gear and enter configuration.
5) Navigate to the controller Configurations button.
6) Select desktop configuration.
7) Search the community for one of many redundant Xbox360 controller presets and choose one.

Once an Xbox360 controller preset is configured, the controller will pretend to be an Xbox controller to most software, so long as Steam is currently running.

**Comment by lawesomes** [comment]
Hi @kode54, not sure if i'm missing something but i followed the instructions exactly but when opening openEmu no input is detect when mapping (Wireless controller). I'm able to map the keyboard controller using the steam controller but the d-pad input is not detected

**Comment by kode54** [comment]
I cannot reproduce. When I configure my Steam controller to be an Xbox360 controller, it reports itself as a Microsoft Official wired controller, not a wireless controller. And I verified that it works with the latest release of OpenEmu.

**Comment by lawesomes** [comment]
Hi @kode54 
I basically did the following:
big picture mode > configuration > base configuration > desktop configuration (Selected the gamepad template and also the community template "Xbox Configuration".

I then added OpenEmu as a non steam game, launched and opened the Configuration panel in Open Emu and tried to map the wired controller for Snes. Did i misunderstand the instructions?

**Comment by kode54** [comment]
It is not necessary to add OpenEmu as a non-Steam game.

It is, however, necessary to open the input configuration and select the Wired controller from the inputs list, where it may currently list "Keyboard".

**Comment by lawesomes** [comment]
Thanks!, I worked it out. You are correct, this method works perfectly. I think it was related to the launch settings i had on the application shortcut within steam. Thx for the help!

**Pull request merged**
