### PR TITLE
Implement rewinding

### PR DESCRIPTION
**Pull request by kylewlacy**
This PR updates the interface for save states, and enables rewinding for Game Cores that conform to the new interface.

The new save state interface consists of the following 2 methods in `OEGameCore`:

    + (NSData)serializeStateWithError:(NSError **)outError;
    - (BOOL)deserializeState:(NSData *)state withError:(NSError **)outError;

By default, `saveStateToFileAtPath:` and `loadStateFromFileAtPath:`  call `serializeStateWithError:` and `deserializeState:withError:`, which means a Game Core can either implement only the former set (which means rewinding is unavailable), or it can implement the latter, meaning that saving/loading is taken care of automatically through `NSData`s.

Rewinding works by calling `serializeStateWithError:` every frame, and saving the result in an `NSArray` (see [`OEGameCore.m` line 239](https://github.com/kylewlacy/OpenEmu-SDK/blob/196c2a2487450711a154530d9dc05eecc6eee470/OpenEmuBase/OEGameCore.m#L239)). To rewind, states are removed from the array and deserialized before the frame is executed (see [`OEGameCore.m` line 214](https://github.com/kylewlacy/OpenEmu-SDK/blob/196c2a2487450711a154530d9dc05eecc6eee470/OpenEmuBase/OEGameCore.m#L214)).

I also uncommented the code for the rewind controls, so it appears in the control preferences as you would expect. Just like fast forwarding, rewinding is non-analog.

### CODE REVIEW

**Comment by clobber** [comment]
Hey there. Thank you for the PR!

We are definitely interested in implementing rewind support, as we've had a working version sitting in this branch that we've neglected to merge in for some time: https://github.com/OpenEmu/OpenEmu/tree/proto_rewind

That branch is more efficient in dealing with memory but may need a few tweaks. Would you be willing to work with that code and adapt it into yours?

**Comment by kylewlacy** [comment]
@clobber Sure, I can do that

**Comment by kylewlacy** [comment]
Okay, done! I added `OEDiffQueue`, which is based on the `OERewindBuffer` class from the `proto_rewind` branch. The main difference is that it isn't initialized with a fixed size, so when a new `NSData` is pushed onto the queue, it can be any length (including 0), and popping again will return an `NSData` of the same length.

Another change is that it uses `char`s instead of `uint32_t`s. This is because, if an `NSData` is passed in with a length of, say, 9, that means we would do the following:

```objc
uint32_t *nextBytes = (uint32_t)[data bytes];
_currentBytes[0] = nextBytes[0]; // copy bytes 0, 1, 2, 3
_currentBytes[1] = nextBytes[1]; // copy bytes 4, 5, 6, 7
_currentBytes[2] = nextBytes[2]; // copy bytes 8, 9, 10, 11 (BAD!)
```

Hence, bytes 9, 10, and 11 would also be copied, which are out of the bounds of the `nextBytes` array.

**Comment by clobber** [comment]
Thanks for adapting in that code! Okay, just reviewing here:

* uint32_t isn't an issue. You're adding a 2x or more performance hit with char

* I'm a bit worried about performance impacted by saving state every single frame. In the original implementation we did it every 3rd frame so we should figure out a reasonable interval. https://github.com/OpenEmu/OpenEmu/commit/ec060c55ad9a49b0fa507964511ef334fd089e41#diff-dc4d32fb11cf98852b961e075e37dd50R211 We can also expose it by a setting later.

* Throttling: we need to do this for both max rewind buffer length and the step of the buffer.
   * Max rewind buffer length should be a function of time, so if we wanted 30 seconds of rewind buffer:
`SaveSize * (FrameRate/Step) * 30`, where SaveSize may be variable
   * We can also expose the max buffer length time by a setting later

* Also, we want to make sure that recording for rewind doesn't happen while fast forwarding is happening.

**Comment by kylewlacy** [comment]
1) Casting a byte array to `uint32_t*` to copy bytes in this situation results in undefined behavior. Let's say that a byte array of length 11 is passed in to `[OEDiffQueue push:]`:

    char*     bytes  - 01|02|03|04|05|06|07|08|09|0A|0B
    uint32_t* points - 01 02 03 04|05 06 07 08|09 0A 0B xx

When we try to read `points[2]`, we get bytes `09 0A 0B xx` (where `xx` is some out-of-bounds value; probably '0', but it could be anything). Again, this is undefined behavior in C. I'm not intimately familiar with memory management on OS X/Darwin, so it's entirely possible that this behavior *is* documented for OS X (in which case, I'd be more than happy to use the implementation you provided to do the copying). Otherwise, it's entirely possible that this code can cause a segfault.

I was also curious to see what the performance impact of using `char` vs `uint32_t` really was, so I wrote three different implementations. First, the form that I originally provided, using `char`s in `OEDiffQueue`. Second, replacing the use of `char` with `uint32_t`, and changing the appropriate calculations. Third, using `uint32_t`, and specifically checking if we would be reading out of bounds (and either copying by `uint32_t`, or casting to `char*` and reading the final 1, 2, or 3 bytes that way). You can see the implementation for this [here](https://gist.github.com/kylewlacy/ace01cea2a1ce19f9412#file-oediffqueue-mm-L33-L35), where you can use a `typedef` to change the type, and a `#define` to toggle bounds checking. Here's a table showing the performance differences over 5 runs (benchmarked using `OEPerfMonitorObserve` [around these lines](https://gist.github.com/kylewlacy/ace01cea2a1ce19f9412#file-oegamecore-benchmark-m-L208-L242) while playing Super Mario Bros. 1 with [my experimental Nestopia core](https://github.com/OpenEmu/Nestopia-Core/pull/1)):

          |uint32 (no checks)|uint32 (checks)|char
--------|------------------------|---------------------|------
Run 1|826.0 fps|920.5 fps|908.0 fps
Run 2|851.8 fps|951.5 fps|965.2 fps
Run 3|1120.1 fps|925.3 fps|928.7 fps
Run 4|899.4 fps|1061.0 fps|994.6 fps
Run 5|947.9 fps|906.7 fps|952.8 fps
**Average**|**946.7 fps**|**958.3 fps**|**949.9 fps**

For completeness' sake, I also ran each variation with Instruments to see the actual CPU time `OEDiffQueue` was using:

                             |Percentage of Time
------------------------|--------------------------
uint32 (no checks)|[0.7%](http://cl.ly/ZtTo/uint32-no-check-cpu.png)
uin32 (checks)|[0.8%](http://cl.ly/Zsxb/unit32-check-cpu.png)
char|[1.2%](http://cl.ly/ZsnW/uint8-cpu.png)

From these benchmarks, I don't see any reason to prefer using `uint32_t*` over `char*`, considering it adds quite a bit of complexity for next to no performance gain. I'd certainly like to see someone else run the tests themselves, and, again, I'd be more than happy to integrate it if someone found a bigger performance gap than I did.

2) As you may have seen from the screenshots in the above table, state serialization takes about 2% CPU time when running a game (which isn't a significant amount). So, I decided to see the memory impact of saving every 'N' frames for rewinding ('1' is saving every state, '2' is saving every other state, etc.), for about a minute of Super Mario Bros. gameplay (with [this implementation](https://gist.github.com/kylewlacy/ace01cea2a1ce19f9412#file-openemugamecore-skipping-m-L227-L240)):

Saving N frames|Memory Usage
----------------------|--------------------
1|[10.44 MB](http://cl.ly/ZtLJ/mem-use-1.png)
2|[6.73 MB](http://cl.ly/ZtgT/mem-use-2.png)
3|[4.01 MB](http://cl.ly/Zt0B/mem-use-3.png)
4|[4.08 MB](http://cl.ly/ZtlQ/mem-use-4.png)
5|[3.00 MB](http://cl.ly/ZtEN/mem-use-5.png)

As you can see, there's marginal returns for increasing the number of frames skipped for rewind recording. From an end-user's standpoint, recording every frame seems to be the best answer anyway: I've been playing extensively with the rewinding feature in it's current state, and being able to rewind at 1x feels 'right' (and it's how Nestopia's rewinding works, if I'm not mistaken). I'd certainly suggest you try each variation to judge for yourself, though.

I'd be okay adding a setting to change this interval, but it feels like a bit of a compromise to me. Honestly, OpenEmu is one of the most polished open source projects I've seen, and the core philosophy on the homepage is that "it just works". As an end user, I love that OpenEmu has very few 'cryptic' settings that you tend to see in other emulators. That said...

3) I think that adding a setting for the *length* of the rewind buffer is a much better idea. This would have a much more notable impact on memory use, and seems like it's just an easier option to understand. Additionally, allowing the user to set the length to '0' provides an intuitive way to turn off rewinding altogether. I'll be adding support for this in `OEDiffQueue` as soon as I can.

4) I don't see any reason to disable recording states while fast forwarding. Again, I've been playing extensively with rewinding for the last few days. Accidentally over-fast-forwarding tends to be one of the most common reasons for me to rewind.

I'd also like to bring up that, currently, holding rewind and fast forward at the same time does an accelerated rewind. To me, this feels like the most natural result, but I'd be curious to hear if you had a different idea as to what this should do?

**Comment by clobber** [comment]
1) Thank you for the benchmarks. I've yet to run these but I will do it later tonight, making sure to build for release mode and checking both the frontend and core since the results didn't 'look right' to me. 

Regarding overall performance: I really want to makes sure we get this right, because we already have a few outstanding issues right now affecting the app (see https://github.com/OpenEmu/OpenEmu/issues/953) and I don't want to compound that. Also, users are still running on Core 2 Duo's (myself included :P). So any CPU and Mem savings are welcome, especially where battery life is concerned and this being an always-on feature.

2) Some emulator cores will be utilizing more resources, especially ones like Mupen64Plus. I also feel that 10MB vs 4MB after running a minute with a 3 frame interval are pretty significant savings since this will especially add up depending on how long we set the buffer time (and depending on the emulator core in use).

So let's add a setting to change this interval but just default it to '1' interval for now -  that's fine and I'll play around with it myself to see how rewind feels. Later I'll add hooks so that we can possibly tweak it on a per-core or global basis, likely through the `OEGameCoreOptions` keys we use in the cores .plist's right now. 

Sorry, I wasn't clear: we'd never expose a setting like this to the users through the frontend! We may hide it away in our 'debug prefs' if devs need to test and play around with it through here: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Preferences:-Secrets

3) Let's definitely also add a setting for buffer length time. We'll decide on reasonable defaults later - maybe start with 30 seconds or 1 minute for now. I may expose this setting to the frontend, but we'd generally like to have rewind 'just work' and not burden users on having to decide how long the buffer ought to be. We'll see though, as we enable rewind in other emulator cores and test.

Good call on the disabling rewinding too - I forgot to mention that in the review. Let's have a setting to disable rewind completely, since cores like PPSSPP with 13-25MB save states + delta frames could never reasonably support this. Some cores are also much slower at serializing.

4) I was under the impression that recording frames would break or cause an issue while fast forwarding (wasn't sure the emulator cores could handle that to be honest, maybe some of them won't be able to as we speed up their run loop and record at the same time...I can see the being a problem for ones that aren't coded so well). I assume testing has only been done on Nestopia so we can't be sure, but if it's fine for now then we'll leave the behavior as-is.

5) Accelerated rewind! That's kind of interesting. Sure, let's keep it if you like that. We thought about having *slower* speeds to rewind back at, but would possibly require setting up a display link to feed the data from the rewind buffer in at a slower rate or keep feeding the same frame into the emulator over and over - probably too much work than it's worth right now.

Anyway, thanks again for bearing with us! You've done an excellent job and we're excited to have rewind implemented soon. This will be another nice feature to include in our next release full of nice new features :)

**Comment by clobber** [comment]
Okay, and just to follow up with benchmarking:

`uint32`:
round 1: https://gist.github.com/anonymous/9559076f6b77e73d6fff
round 2: https://gist.github.com/anonymous/b6f629ef50724d303d10

`char`: 
round 1: https://gist.github.com/anonymous/ef99925af161782ecba1
round 2: https://gist.github.com/anonymous/1dfe670bc242fc8d7f8d

Hard to argue that there is a significant difference and vectorization is great in clang, so let's use `char`

Thanks again for the benchmarks!

**Comment by kylewlacy** [comment]
Okay, adding the rewind interval and buffer length options as core settings makes a lot more sense! I also didn't mean that a 4MB memory reduction was *worthless*, only that the improvements are marginal; there's a big gap between a rewind interval of 0 and 1, but a smaller gap between 1 and 2, an even smaller gap between 2 and 3, and so on. It seems much more worthwhile to reduce the rewind buffer length, at least in this case. But, as you mentioned, it's probably useful to have the *option* to change it per-core, since the exact difference in memory use will probably vary a *lot* per-system, and per-emulator.

Anyway, I added a new initializer for `OEDiffQueue`, which takes a capacity. Items added beyond `capacity` are dropped from the bottom of the queue. To improve performance, `OEDiffQueue` uses `std::deque` internally, which has O(1) for adding and removing items from both the beginning and end (quick benchmarking showed about a 30% speed boost or so within `[OEDiffQueue push:]` with `std::deque` instead of `std::vector`, once the queue reaches maximum capacity). Currently, an `OEGameCore` never initializes with an explicit capacity, so it defaults to 'unlimited' (really `NSUIntegerMax`, which, [is about 10 billion years' worth of states](http://www.wolframalpha.com/input/?i=%282%5E64%2F60%29+seconds)...)

I also added `[OEGameCore canRewind]` and `[OEGameCore rewindInterval]`, which default to `YES` and `0` respectively. The former controls whether or not a core is allowed to rewind, and the latter controls how many frames to skip when recording states for rewinding ('0' records every frame, '1' records every other frame, etc; just like the `proto_rewind` implementation). `canRewind` makes no difference if a core hasn't implemented `serializeStateWithError:`.

`OEGameCore`'s `canRewind` and `rewindInterval` properties, as well as `OEDiffQueue`'s capacity default to constants, but it should be pretty simple to rewrite them to load from the core's options (although I'm not familiar enough with the codebase to say what the best way to introduce this setting is, maybe a new set of methods in `OEGameCoreController`?)

**Comment by clobber** [comment]
This looks great!

One thing: for `[OEDiffQueue initWithCapacity:]` I'm thinking we need to express it in terms of time, but not completely sure if OEDiffQueue should 'know' about time. But, we really do need to have it so we tell the core "okay, keep recording for 30 minutes max" instead of having to think about it in terms of size from a settings perspective. Especially if we exposed a global or per-core setting through the UI.

What if when we create `OEDiffQueue` it inits as `TimeInSeconds * frameInterval` (e.g. 1800 * 60) where we `initWithCapacity:` the seconds grabbed from the core plist file? Would that work for the buffer?

As for storing the core options in the plist, it'll work like this commit: https://github.com/OpenEmu/Nestopia-Core/commit/7cb3da0060bbe792b7350ef0112d5340789ff955

So for each system (both NES and FDS since `OEGameCoreOptions` is designed for support of multi-systems in cores) I think we could have keys, for example:
* `<key>OEGameCoreSupportsRewind</key><true/>` = (required) to opt-in the core to enable rewinding, default it should be off in OEGameCore.
* `<key>OEGameCoreRewindBufferSeconds</key><integer>1800</integer>` = (required) this tells the core how long in seconds to create the `OEDiffQueue` buffer, so its not unlimited.
* `<key>OEGameCoreRewindInterval</key><integer>0</integer>` = (optional) this sets the rewind interval for how often to record frames, in case we need it for some cores. '0' being the default in OEGameCore to record every frame.

For implementation of these methods, yeah, I think they'll have to go in `OEGameCoreController` much like this commit (https://github.com/OpenEmu/OpenEmu-SDK/commit/ab1c70083397b36efb1b962ba45d9589f1598269) to spit back those keys to the frontend if they exist where I'll read them in `OEGameDocument` (https://github.com/OpenEmu/OpenEmu/commit/42fb296edf22b9804ba32600e7627e668aaad3fb). From there I'll have to decide how to send the message back to `OEGameCore` to enable rewind, set the buffer seconds and possible interval. I think it travels from `OEGameDocument` to OEGameCoreManager->OEHelperApp->OEGameCore by calling a method like `[_gameCoreManager setRewind:YES]` ... maybe there's a cleaner and easier way :P

Anyway, let me know what you think about 'time' and the rest. I think after that we can go ahead and merge this in.

Thank you!

**Comment by kylewlacy** [comment]
Just doing `[OEDiffQueue initWithCapacity:30*60]` for the rewind buffer would limit it to 1,800 states, or 30 seconds, so doing `[OEDiffQueue initWithCapacity:time*frameInterval]` should work as expected! The 'gotcha' is accounting for the rewind interval, so it should really be `[OEDiffQueue initWithCapacity:(time*frameInterval) / (rewindInterval+1)]` (although, then there's the issue of rounding vs. truncating; I think it would be a good idea to round up the capacity).

As for the settings, couldn't `canRewind` be written like this?
```objc
// OEGameCoreOptions.m
- (BOOL)supportsRewindingForSystemIdentifier:(NSString *)systemIdentifier
{
    id options = [self coreOptions];
    id system = [options valueForKey:systemIdentifier];
    return [[system valueForKey:OEGameCoreSupportsRewindingKey] boolValue];
}

// OEGameCore.m
- (BOOL)canRewind
{
    return [[self owner] supportsRewindingForSystemIdentifier:[self systemIdentifier]];
}
```
That's just an idea; I'm probably overlooking something...

Anyway, I've also been looking into adding support for rewinding in other cores. So far, I've finished Nestopia, FCEU, and Higan. I also added support in SNES9x, but it's still pretty buggy (and I'm not sure if it's because of OpenEmu's integration with SNES9x, or if SNES9x's state system is just really janky... I think it might actually be the latter). I'd like to do the Mupen64 core next, but it's pretty clear that there's no easy way to do it without making some changes to Mupen64 itself (there's no API for reading from/writing to a buffer or a file handle, so the internal saving/loading functions need to be refactored).

**Comment by clobber** [comment]
Good catch with the `rewindInterval` -- I didn't think about that! This looks nice and yeah we should just round up the capacity since it won't be much.

Settings:
I made it needlessly complex in my head because I was thinking about a global toggle through the UI. Your version is much simpler and works great; I just tested it out. Let's go with that and we can do the same for reading the `rewindInterval` and `bufferSeconds`.

Core updates:
Some of the cores are in desperate need of update so I am going to sync with upstream for FCEU (http://sourceforge.net/p/fceultra/code/HEAD/tree/fceu/trunk/), Gambatte (https://github.com/sinamas/gambatte) and VBA (http://sourceforge.net/p/vbam/code/HEAD/tree/trunk/) and then cleanly re-port them since they are all currently using older API that just gets in our way. I realize then we may have to add our own hooks to some for mem-based serialization, but it'll be better this way. I will get to updating those core ports this week and then feel free to add rewind support.

I checked upstream with SNES9x (https://github.com/snes9xgit/snes9x) and they're kind of in a perpetual beta, but I noticed they added functions for `S9xFreezeGameMem()`, `S9xUnFreezeGameMem()` and `S9xFreezeSize()` which I believe will help us if you want to take those and merge them in our port. That should solve the problem with that core I hope.

By the way, would you like commit access? That way it'll be easier to update everything you'd like to work on.

**Comment by kylewlacy** [comment]
Once SNES9x gets merged, I'll see how well these new functions work, since they sound exactly like what we want.

Sure, commit access would be awesome! I have no problem pushing a quick fix or something (such as implementing rewind support for all the cores), but I'll probably end up making a lot of PR's for new features anyway (and I have quite a lot of things in mind!), since I really value this sort of open discussion on GitHub

**Comment by clobber** [comment]
Just sent you the invite for commit access!

So I've just finished cleanly re-porting FCEUX to the last stable: https://github.com/OpenEmu/FCEU-Core

All the mem stream functions that were previously there are gone, so you'd have to reimplement those to get rewind functionality back. Next up are Gambatte and VBA for this weekend. Then I'll look at bringing over those `S9xFreeze` state functions for SNES9x.

As for this PR, I think we just need the last items we talked about and then we're good to merge! Let me know when you're ready.

**Comment by kylewlacy** [comment]
Okay, I added support for the plist keys to indicate that a core supports rewinding. I already [added support for this in Nestopia](https://github.com/OpenEmu/Nestopia-Core/pull/1). Also, I found out FCEU *does* still have a way to serialize to memory, [using a memory-only `EMUFILE*` instance](https://github.com/OpenEmu/FCEU-Core/blob/98acf529e88462c0861e976b9a1e5a578c517811/src/emufile.h#L122) (which I've already implemented in my local working copy; I'll push to master once this PR gets merged). So, looks like this PR is finally ready to be merged then!

...

Actually, one *minor* thing I wanted to bring up that's been bothering me: the changes I originally made to the `saveStateToFileAtPath:completionHandler:`/`loadStateFromFileAtPath:completionHandler:` methods.

Currently, if the new `serializeStateWithError:` and `deserializeState:withError:` methods are implemented, the callbacks passed to the `saveStateToFileAtPath:completionHandler`/`loadStateFromFileAtPath:completionHandler:` methods will never receive an error when using the default implementation, even if the `serializeStateWithError:`/`deserializeState:withError:` methods set one. This is because of how I did the API deprecation:

```
            (caller)    *nil*
               ||        /\
               ||        ||
               \/        ||
__________________________________________
|saveStateToFileAtPath:completionHandler:|
------------------------------------------
               ||       *nil*      <==== Whoops, the previous error
               ||        /\              gets lost in transit
               \/        ||
         ________________________
         |saveStateToFileAtPath:|
         ------------------------
               ||      *error*
               ||        /\
               \/        ||
        __________________________
        |serializeStateWithError:|
        --------------------------
```

That is, `saveStateToFileAtPath:completionHandler:` calls `saveStateToFileAtPath:`, which, in turn, calls `serializeStateWithError:` while discarding the `error` value. The following would be more ideal:

```
    (caller)    *nil*                   (caller)   *error*
       ||        /\                        ||        /\
       ||        ||                        ||        ||
       ||        ||                        \/        ||
       ||        ||         __________________________________________
       ||        ||         |saveStateToFileAtPath:completionHandler:|
       ||        ||         ------------------------------------------
       ||        ||                        ||      *error*
       ||        ||                        ||        /\
       \/        ||                        ||        ||
 ________________________                  ||        ||
 |saveStateToFileAtPath:|                  ||        ||
 ------------------------                  ||        ||
       ||      *error*                     ||        ||
       ||        /\                        ||        ||
       \/        ||                        \/        ||
__________________________          __________________________
|serializeStateWithError:|          |serializeStateWithError:|
--------------------------          --------------------------
```

That is, `saveStateToFileAtPath:` and `saveStateToFileAtPath:completionHandler:` could have independent implementations, where both call `serializeStateWithError:`, where the former discards the error value, and the latter calls its completion handler with the error value.

The problem is that this breaks API compatibility: from what I can tell, the idea was that a game core could get away with implementing `saveStateToFileAtPath:` only; any game core that did that would break, since `saveStateToFileAtPath:completionHandler:` would no longer call the isolated `saveStateToFileAtPath:`.

So here's what I'm thinking:

```
            (caller)             *error*
               ||                  /\
               ||                  ||
               \/                  ||
__________________________________________
|saveStateToFileAtPath:completionHandler:|
------------------------------------------
                  |    |         *error*
                  | /\ |           /\
                 / /  \ \          ||
               / /      \ \        ||
              |_          _|       ||
________________________ __________________________
|saveStateToFileAtPath:| |serializeStateWithError:|
------------------------ --------------------------
   *nil*      ||
    /\        ||
    ||        \/
__________________________
|serializeStateWithError:|
--------------------------
```

`saveStateToFileAtPath:completionHandler:` will attempt to call `serializeStateWithError:` first. If a valid `NSData*` is returned, the data is saved to a file. If `nil` is returned AND a valid error value is returned, the completion handler will get called with the returned error. Otherwise, `saveStateToFileAtPath:` gets called, and the completion handler gets called with no error value.

This hierarchy would look something like this in code:

```objc
- (BOOL)saveStateToFileAtPath:(NSString *)fileName completionHandler:(Block)block
{
    NSError *error = nil;
    NSData *data = [self serializeStateWithError:&error];
    if(data)
    {
        NSError *writeError = nil;
        BOOL result = [data writeToFile:fileName options:0 error:&writeError];
        block(result, writeError);
    }
    else if(error)
    {
        block(NO, error);
    }
    else
    {
        block([self saveStateToFileAtPath:fileName], nil);
    }
}

- (BOOL)saveStateToFileAtPath:(NSString *)fileName
{
    NSData *data = [self serializeStateWithError:nil];
    if(data)
    {
        BOOL result = [data writeToFile:fileName options:0 error:nil];
        return result;
    }
    else
    {
        return NO;
    }
}
```

(This is just the first solution that comes to mind). Let's say that a game core uses these default implementations, then implements `serializeStateWithError:`. The problem here is that, if `[self saveStateToFileAtPath:completionHandler:]` gets called, and `serializeStateWithError:` fails by returning `nil` (for a legitimate reason— not because it isn't implemented) and also doesn't return an error value, then `serializeStateWithError:` will get called twice (once in `saveStateToFileAtPath:completionHandler:`, then again in the fallback call to `saveStateToFileAtPath:`).

I just wanted to get your thoughts on this (and I'm also hoping I just missed an obvious, simpler solution). Otherwise, I'll just implement this version tomorrow, and finally merge this PR.

**Comment by astrange** [comment]
Cocoa conventions are for any method that can set an error, to always do so if nil is returned.

So even if there's a legitimate reason, it should return an error expressing that reason.

**Comment by astrange** [comment]
Also, I think OEGameCore should only contain methods to be implemented by subclasses - so the save:completionHandler: methods should go, and maybe things like frameRefreshThread:. They can go to the helper or OEGameCoreController or something. But since your work is already done, we don't need to hold it up for that!

**Comment by kylewlacy** [comment]
I didn't know about that convention, that makes sense then!

--------------------------------------------------------------------------

I agree that some methods in `OEGameCore` should be moved out, especially `frameRefreshThread:`; I'll probably start working on that next. However, I think all 6 of the saving/loading methods need to stay in `OEGameCore` (for the time being), since all 6 can be overloaded in subclasses at the moment (and I don't think all cores will be able to support state serialization/deserialization).

**Comment by clobber** [comment]
I have the urge to merge!

**Comment by clobber** [comment]
Update:

I fell a bit behind schedule this week, but I just finished up a clean port of VBA (https://github.com/OpenEmu/VisualBoyAdvance-Core) if you'd like to take a look at rewind support in that core. It looks like the functions that might help are `CPUReadMemState` and `CPUWriteMemState`. Up next is Gambatte which I should finish fairly quick and then I'll merge in those functions we need for SNES9x!

**Comment by kylewlacy** [comment]
Okay, thanks for the heads up! I've been having some issues with OS X for the past few days, but I should be back on track on adding support for more cores this week!

**Comment by kylewlacy** [comment]
@clobber Just a quick update:

First, I wanted to bring up `VisualBoyAdvance`, which, as you mentioned, added a new set of functions for serializing/deserializing with a buffer. There are two problems with how it's implemented, though: first, it uses `zlib` to compress the in-memory state (and there's no option in the public API to turn it off). Second, the state can only be saved to a fixed-size buffer (kinda like how `snprintf` works). This wouldn't be so problematic, but there's no function to get what size the buffer *will be* (probably because it's compressed).

I tried implementing it by writing a while loop that continually retried serialization (by increasing the buffer size each time), until serialization succeeded. With the additional cost of compression, though, it was *way* too slow to actually keep, so I've stashed this implementation for the time being.

Next, I've gone through all the OpenEmu cores and I've been looking at how each core handles state saving and loading. Here's a quick chart covering how each core handles it:

Core             | States saved using... |Rewinding implemented?
-----------------|-----------------------|-----------------
4DO              | Buffer                |
FCEU             | Buffer                | ✓
GenesisPlus      | Buffer                | ✓
Picodrive        | Buffer                |
PPSSPP           | Buffer                |
TwoMbit          | Buffer                |
VecXGL           | Buffer                |
VisualBoyAdvance | Buffer (Compressed)*  |
Nestopia         | Stream                | ✓
SNES9x           | Stream                |
Stella           | Stream*               | ✓
Atari 800        | Filename              |
Bliss            | Filename              |
blueMSX          | Filename              |
Gambatte         | Filename              |
MAME             | Filename              |
Mednafen         | Filename              |
Mupen64Plus      | Filename (?)          |
NeoPop           | Filename              |
O2EM             | Filename              |
Potator          | Filename              |
ProSystem        | Filename              |
Yabause          | Filename              |
VirtualJaguar    | None?                 |

The cores using buffers or streams (should be) easy to implement, so those are the ones I want to tackle this week.

As you might've guessed, though, most cores depend on a filename to save/load a state. In an ideal world, *every* core would use either a buffer or a stream to save/load states, but I don't see that happening any time soon.

 There's a few different ways I see handling these cores:

- **Modifying emulator code to take a buffer/stream** in addition to a filename. For some cores, this would probably be as simple as changing a private function into a public one. This is (more or less) what I did to add rewinding to Stella: I made the [`Serializer.myStream` member public](https://github.com/OpenEmu/Stella-Core/commit/16bd173e3b88aca0b13f178c963b6888ea4f8bb0?diff=split), which the smallest change I could make to Stella to implement rewinding (which I would be okay with reverting if it's too fragile).

- **Using a FIFO (a named pipe) to save/load states to**. A FIFO in C basically allows you to associate a filename with a stream (in a sense). I've been playing with this idea for a while (you can see an example [here](https://gist.github.com/kylewlacy/688aaa011e7d5acfe3fa)), and it's pretty… odd. First, with some trivial benchmarks, it seems as though using a FIFO is about as fast as using an actual file (although that could be because of temporary caching). Second, certain file operations don't work on FIFO's, most notably `fseek` and `ftell`, which always fail. This could cause issues for emulators that use these methods internally. I also had trouble using a FIFO past the 8KB mark, so it's possible that this strategy won't work at all for certain emulators.

- **Using temporary files**. This is probably the worst-case scenario, since that means we're effectively touching the disk *every frame*. Although, it's possible that this isn't how it would work in practice because of disk write caching. Like I said, a basic benchmark showed that using a real file *appeared* to be about as fast as using a FIFO, but maybe it was because it was such a trivial example and it would be really slow in practice. I'd have to do some benchmarking to see how reasonable this approach actually is.

- **Only implementing rewinding where it makes sense**, such as only supporting emulators that support streams or buffers. This is probably the best option, actually. For some cases, one of the other methods is probably better (like Stella, where it was a single line of code changed to the core), but maybe it'd be best to approach implementing rewinding conservatively?

I've been toying around with using each of these, which is why it's been taking me so long to work on this (as well as life stuff that I've been working on in between). For the most part, each emulator is a completely different challenge to implement, so it'll be a while before I've finished working on every core.

---------------------------------------------------

I also wanted to say thanks for your help! Obviously, I've only been working with the OpenEmu code for a little over a month (which is a short time for a project with 100,000+ LoC), so I'm not familiar with every corner of the codebase yet. It was a much bigger challenge than I expected just to do the rewinding stuff, so it's a ***huge*** help when you give me pointers on what functions to look at, or when you upgrade an emulator core (which is a huge task in its own right)!

**Comment by clobber** [comment]
Hi there, thanks for the update! The table looks great.

For VBA, we will need to modify it enough to suit how we want to do serialization. There is probably enough in this commit for a general idea on handling that, as long as we don't change how saves to disk work: http://sourceforge.net/p/vbam/code/1213/?page=0 and here is an older example for Gambatte https://github.com/libretro/gambatte-libretro/commit/bd7badaa5156436bd2c4b40318dd8a136c727f22

I think out of all the methods you suggested for handling serialization, simply modifying the ones we can and also implementing rewinding where it makes sense is the best approach. Rewind for some of the emulators is unrealistic, especially PPSSPP. Mupen64Plus might be another and MAME has some systems where serialization appears to be unsupported. For some of the emulators that are still under active development and are stuck with filenames for states, we can maybe see about getting some changes upstream too.

Mednafen is a big chunk of our systems, it being multi-system, so some kind of change upstream to accommodate this would be excellent. Oh by the way, here's the commit upstream from SNES9x where they added memstreams. They made a lot of changes but we'd only need to merge the bits for save states https://github.com/snes9xgit/snes9x/commit/9cc05b3c128a0b0e584e6bc5e7b86f4d2da437e0

**Comment by clobber** [comment]
Support for SNES9x added in https://github.com/OpenEmu/SNES9x-Core/compare/622eb6ab8a08...7f5c3ef377fc

@kylewlacy
Hiya, are you still working on these? We're going to try and get a release out as soon as possible (maybe a month or two as long as we've wrapped everything up) and I'd like to make sure we support rewind in most of the 'stable' emulator cores -- namely for the popular systems/emulators such as Gambatte, VBA and possibly Mednafen. All three of those will need modification to the core though.

**Comment by kylewlacy** [comment]
@clobber I stopped working on OpenEmu for a couple weeks to focus on some personal projects. I'll get back to working on the stable cores today though, and I'll get as many done as I can before the release!

**Comment by clobber** [comment]
Thanks! Btw, Ryphecha gave me a hint for Mednafen, so this should require no changes to the core:
```
class MemoryStream : public Stream [...] MemoryStream(uint64 alloc_hint, int alloc_hint_is_size = false);
Stream* s = new MemoryStream(65536);
MDFNSS_SaveSM(s, true); 
[...] MDFNSS_LoadSM(s, true);
```

**Comment by kylewlacy** [comment]
@clobber I've been playing around with the Mednafen and Mupen64 cores, and it looks like neither will be able to support rewinding in the upcoming release. The bottleneck is `[OEDiffQueue push:]`, which seems to struggle with states around 1MB or more (>80% of the CPU time was spent on pushing the state to the queue in my tests with Mupen64). In the future, I'll look into other ways of storing states (such as how [RetroArch](https://github.com/libretro/RetroArch/blob/e67f3f246df7a65eafe9aea86860f213a8d7ef71/rewind.c#L405) does it, for example).

So, for now, FCEU, Gambatte, GenesisPlus, Higan, Nestopia, SNES9x, Stella, TwoMbit, and VisualBoyAdvance all support rewinding. If there's any other major emulators I missed that should be added before the release, feel free to let me know! And, of course, I'll keep adding more later on.

**Comment by loicloic** [comment]
Not (directly) related to the issue at end:

Kyle are you on the IRC channel or not at all ?

**Comment by kylewlacy** [comment]
No, I haven't been on it at all. I could start using it for now on if that makes things easier for everyone though.

**Comment by clobber** [comment]
Since Mednafen is multi-system, we can probably just implement it for its systems we support except for the modules generating large states like PSX and PC-FX. So that'd give us Lynx, TG16/PCE (maybe PCE-CD too), VirtualBoy, and WonderSwan.

For others emulators, definitely CrabEmu since that gives us SG-1000 and ColecoVision (+ its our default 'core' for SMS and GG). Then maybe NeoPop, O2EM and Bliss.

**Comment by kylewlacy** [comment]
Okay, I'll get it done!

**Comment by clobber** [comment]
Supported for Mednafen added in https://github.com/OpenEmu/Mednafen-Core/compare/cbd92afc08a4...20ef96506316

Let me know if anything looks wrong. I've excluded both PSX and PC-FX because their states are >1MB.

So based on the chart above (I've updated it), we're looking pretty good with supported cores and systems. I think CrabEmu would be the last one we really need. Can you work on that one if you get a chance?

**Comment by clobber** [comment]
Support for ProSystem added in https://github.com/OpenEmu/ProSystem-Core/compare/e6d22582c727...2ed73c7f79f3

**Pull request merged**
