### PR TITLE
Add shared schemes for Carthage support

### PR DESCRIPTION
**Pull request by P0ed**

### CODE REVIEW

**Comment by P0ed** [comment]
https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

**Comment by mrvacbob** [comment]
What do we want these for?

**Comment by P0ed** [comment]
Folks using OpenEmu-SDK could use Carthage to build frameworks for them

**Comment by vade** [comment]
Folks using the OpenEmu-SDK have an Xcode project with dependencies and targets. This seems extraneous no?

**Comment by rudyrichter** [comment]
i'm not seeing the benefit either. recommend close.

**Comment by clobber** [comment]
Can't see why anyone would need this.

**Pull request closed without merging**
