### PR TITLE
Fix reading controller bindings saved in OE 1.0.4

### PR DESCRIPTION
**Pull request by shysaur**
Since commit 391ff20dfd64a6e2c1fe44c36dace06b76e043b9, OpenEmu can't read controller binding created in version 1.0.4, because the key names used when encoding/decoding OEHIDEvent changed. The result is the inability to control any game (every input is ignored), and the controller preferences panel shows empty fields for every binding (though it still works, and you can save some new bindings with it).

This PR fixes the issue by adding some code which checks if the data is encoded using the old keys and, if it is, it uses the old keys and logs a warning about it. In my testing I could carry over from 1.0.4 some settings for a keyboard and a Wii Remote.

Another fix would be to change the keys again to the old ones, but I'm not sure about which fix is best.

It has been some time since this bug was introduced, and somebody compiling from source might already have fixed their controls manually, thinking it was some random fluke. But, in general, back-compatibility with unreleased random revisions which are not even declared beta quality is a stupid idea.

Since I don't know which way to go, and key names which end with "Key" are silly, I chose not to revert the key name cleanup.

Feel free to close this PR if you prefer to change the key names back to the old silly ones instead of adding code (nobody's going to see these key names anyway).

### CODE REVIEW

**Comment by rudyrichter** [comment]
is there a reason not to migrate the old bindings file to the new form as part of this load?

**Comment by shysaur** [comment]
Decoding an object is an one-way process. If you set a breakpoint in -initWithCoder:, you will see that the NSCoder passed in is actually an NSKeyedUnarchiver, which can't encode anything.

**Comment by shysaur** [comment]
Plus, not upgrading until it's needed is easier :-) The upgrade will happen automatically when the user changes any of the controller bindings. At that point, the controller bindings file will be regenerated from scratch with the new encoding format (this is already done by existing code).

**Comment by clobber** [comment]
Thanks, but I will probably end up just changing the folder location to work around some other possible headaches I'm thinking of with bindings. The downside of this is that users will need to remap bindings, but it's a small price to pay for peace of mind.

By the way @shysaur, thank you again for all your contributions which have been a huge help. After this next coming release, we'll probably start some more cleanup and modernization efforts so let me know if you are interested in being more involved in the project.

**Comment by shysaur** [comment]
Thanks for the offer! Being an user since the pre-1.0 days, I can't say I'm not interested! Currently I do not have much time, even for my own projects, but I would be glad to help.

**Pull request closed without merging**
